name: main -> Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build:
    name: Building app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.15.0"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Angular Deploy gh-pages Actions
        uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.4.0
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          build_configuration: production
          base_href: /anglo/
          deploy_branch: master
          angular_dist_build_folder: dist/anglo/browser

permissions:
  contents: write
